config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#index'
  get 'home'  => 'pages#home'
  get 'support' => 'pages#support'
  get 'about' => 'pages#about'
  get 'subscribers' => 'subscribers#new'
  get 'contents/confidence-intro' => 'contents#confidence-intro'
  get 'contents/accepting' => 'contents#accepting'
  get 'contents/motivation-intro' => 'contents#motivation-intro'  
  resources :accounts
  resources :subscribers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  def admin?
    has_role?(:admin)
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) 
    devise_parameter_sanitizer.permit(:sign_in) 
    devise_parameter_sanitizer.permit(:account_update) 
  end
  
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate_user!
  layout 'application'
  def confidence
  end

  def motivational
  end
  def accepting
  end
  #figure out maybe a better system
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'application'
  def index
  end

  def home
  end

  def support
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def new
        super
        
    end
    protected
    def after_sign_up_path_for(resource)
        '/subscribers/new'
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
    before_filter :authenticate_user!
    
    def new
    end
    def create
    end
    def show
        token = params[:stripeToken]
        
        customer = Stripe::Customer.create(
            card: token,
            plan: 1020,
            #email: current_user.email
        
            )
            current_user.subscribed = true
            current_user.stripeid = customer.id
            current_user.save
            
             redirect_to root_path, notice: "Your subscription was set up successfully!"
    end
    def update
    
        token = params[:stripeToken]
        
        customer = Stripe::Customer.create(
            card: token,
            plan: 1020,
            #email: current_sign_in.email
        
            )
            current_user.subscribed = true
            current_user.stripeid = customer.id
            current_user.save
            
             redirect_to root_path, notice: "Your subscription was set up successfully!"
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/contents/_playlist.html.erb
<!--
<div id="cssmenu">
<ul>
   <li class="active"><a href="#"><span>Intro</span></a></li>
   <br/>
   <div id = "playlist-section"><p>Changing your mindset</p></div>
   <li><a href="#">Being more positive</a></li> 
   <li><a href="#">Strengths and Weakness</a></li> 
   <li><a href="#">Accepting</a></li> 
   <li><a href="#">Focus</a></li> 
   <div id = "playlist-section"><p>Body language</p></div>   
   <li><a href="#">Posture</a></li>
   <li><a href="#">Smiling</a></li> 
   <li><a href="#">Eye Contact</a></li>
   <li><a href="#">Speech</a></li>   
   <div id = "playlist-section"><p>Motivation</p></div>   
</ul>
</div>

-->
<div id="playlist">
<html ng-app="demo">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
  </head>
  <body ng-controller="appCtrl">
    <section>
      <div class="container">
        <ul class="flowGrid" ng-flow-grid="demoGird" min-item-width="200">
          <li class="flowGridItem" ng-repeat="video in confidence | filter:searchText">
                  <a href="{{ video.link }}"><img ng-src="{{video.img}}"></a>
                  <div id="item-bar-bot">
                  <p>{{ video.name }}</p>
              </div>
          </li>
        </ul>
      </div>
    </section>
  </body>
</html>
</div>

app/views/contents/accepting.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="video">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/qFvATzBTn_s?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
</div>
<br/>
<div id="title-video">
    Centuries (Death Note AMV)
</div>
<br>
<div id="desc-video">
    No description
</div>
<br>
<br>
<%= render '/contents/playlist' %>

app/views/contents/confidence-intro.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="video">
    <!-- <iframe width="889" height="500" src="https://www.youtube.com/embed/hyEsiwc0ys4?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe> -->
    <iframe width="889" height="500" src="https://www.youtube-nocookie.com/embed/pq1CGm7t97A?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
</div>
<br/>
<div id="title-video">
    Intro
</div>
<br>
<div id="desc-video">
    Welcome to ConfidentMindset!
</div>
<br>
<br>
<%= render '/contents/playlist' %>

app/views/layouts/_nav.html.erb
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
 <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
<meta name="apple-mobile-web-app-capable" content="yes" />
  <style>
.navbar {
    margin: 0;
    border: 0;
}
    html body {
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
        margin: 0;
    }
</style>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ConfidentMindset</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">About</a></li> -->
        <li><%= link_to('Sign Up', new_user_registration_path) %></li>
        <li><%= link_to('Sign In', new_user_session_path) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CM</a>
    </div>
  <style>
.navbar {
    margin: 0;
    border: 0;
}
</style>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" ng-model="searchText">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to('Settings', edit_user_registration_path) %></li>
            <li><a href="/support">Support</a></li>
            <li role="separator" class="divider"></li>
             <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Confidence</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/nav' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<% if user_signed_in? %>
  <% if  current_user.subscribed? %>
  <br>
  <html ng-app="demo">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
      <style type="text/css">
      /*------------------------*/
      #item-bar-bot
      {
        background-color: white;
        width: 218px;
        height: 50px;
      }
      p
      {
          font-size: 20px;
      }
      .flowGrid
      {
        position: relative;padding: 0;
        
      }
      .flowGrid:before,.flowGrid:after
      {
          content: "";
          display: table;
      }
      .flowGrid:after{
          clear:both;
      }
      .flowGridItem
      { 
        list-style: none;
        
      }
      .flowGridItem img
      {
        width:100%;
        
      }
      .flowGridColumn
      {
          float: left;
          padding-left: 10px;
      }
      .flowGridColumn:last-of-type
      {
          /*padding-right: 10px;*/
      }
      /*---------- demo page only--------------*/
      header{
        background-color: #efefef;
        margin-bottom: 25px;
        height: 250px;
        text-align: center;
      }
      </style>
    </head>
    <body ng-controller="appCtrl">
      <section>
        <div class="container">
          <ul class="flowGrid" ng-flow-grid="demoGird" min-item-width="200" max-item-width="300">
            <li class="flowGridItem" ng-repeat="item in items | filter:searchText">
                    <a href="{{ item.link }}"><img ng-src="{{item.img}}"></a>
                    <div id="item-bar-bot">
                    <p>{{ item.name }}</p>
                </div>
            </li>
          </ul>
        </div>
      </section>
    </body>
  </html>
<% else %>

  <script type="text/javascript">
    window.location.href="/subscribers/new"  // put your correct path in a string here
  </script>
<% end %>
<% else %>
<body id="login">
<% if false %>

<% end %>

	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,600,300,200&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<body>

	<!-- === Arrows === -->
	<div id="arrows">
		<div id="arrow-up" class="disabled"></div>
		<div id="arrow-down"></div>
		<div id="arrow-left" class="disabled visible-lg"></div>
		<div id="arrow-right" class="disabled visible-lg"></div>
	</div><!-- /.arrows -->


	<!-- === MAIN Background === -->
	<div class="slide story" id="slide-1" data-slide="1">
		<div class="container">
			<div id="home-row-1" class="row clearfix">
				<div class="col-12">
					<h1 class="font-semibold">CONFIDENT <span class="font-thin">MINDSET</span></h1>
					<h4 class="font-thin">Weekly <span class="font-semibold">premium videos to change your </span> life.</h4>
					<br>
					<br>
				</div><!-- /col-12 -->
			</div><!-- /row -->
			<div id="home-row-2" class="row clearfix">
				<div class="col-12 col-sm-4"><div class="home-hover navigation-slide" data-slide="4"><img src="../c3.png"></div><span>PROFESSIONAL</span></div>
				<div class="col-12 col-sm-4"><div class="home-hover navigation-slide" data-slide="3"><img src="../c2.png"></div><span>PROVEN</span></div>
				<div class="col-12 col-sm-4"><div class="home-hover navigation-slide" data-slide="5"><img src="../c1.png"></div><span>AFFORDABLE</span></div>
			</div><!-- /row -->
		</div><!-- /container -->
	</div><!-- /slide1 -->

		<!-- === Slide 3 === -->
	<div class="slide story" id="slide-3" data-slide="2">
		<div class="container">
			<div class="row title-row">
				<div class="col-12 font-thin">How <span class="font-semibold">it</span> works </div>
			</div><!-- /row -->
			<div class="row subtitle-row">
<div class="list-group">
  <a class="list-group-item active">
    <h2 class="list-group-item-heading">Watch the tutorials</h2>
    <p class="list-group-item-text">You will receive a video per week</p>
  </a>
</div>
<br>
<div class="list-group">
  <a class="list-group-item active">
    <h2 class="list-group-item-heading">Follow the exercises</h2>
    <p class="list-group-item-text">Think of it as daily goals</p>
  </a>
</div>
<br>
<div class="list-group">
  <a class="list-group-item active">
    <h2 class="list-group-item-heading">Improvement</h2>
    <p class="list-group-item-text">Great changes are coming</p>
  </a>
</div>
			</div><!-- /row -->
      
		</div><!-- /container -->
	</div><!-- /slide3 -->

	<!-- === Slide 2 === -->
	<div class="slide story" id="slide-2" data-slide="2">
		<div class="container">
			<div class="row title-row">
				<div class="col-12 font-thin">What <span class="font-semibold">will you </span> get </div>
			</div>
			<br>
			<div class="row line-row">
				<div class="hr">&nbsp;</div>
			</div><!-- /row -->
			<div class="row subtitle-row">
				<div class="col-12 font-thin"> <span class="font-semibold">Benefits</span></div>
			</div><!-- /row -->
			<div class="row content-row">
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon icon-eye-open"></i></p>
					<h2 class="font-thin"> <span class="font-semibold">Relationships</span></h2>
					<h4 class="font-thin">Build stronger relationships. Make more friends, build powerful connections, be more attractive and have fun while doing it. </h4>
				</div><!-- /col12 -->
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon icon-laptop"></i></p>
					<h2 class="font-thin">Self <span class="font-semibold">Happiness</span></h2>
					<h4 class="font-thin">You will learn how to love your body. Your self happiness will increase exponentially.</h4>
				</div><!-- /col12 -->
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon icon-tablet"></i></p>
					<h2 class="font-thin"> Career <span class="font-semibold">Success</span></h2>
					<h4 class="font-thin">Being confident has a strong correlation on being succesful. Have the drive to start things, ability to standup for yourself, destroy your fears, and believe in themselves.</h4>
				</div><!-- /col12 -->
				<div class="col-12 col-lg-3 col-sm-6">
					<p><i class="icon icon-pencil"></i></p>
					<h2 class="font-semibold">Fearless</h2>
					<h4 class="font-thin">Imagine being fearless. How good would that feel? With our help, we can get you to that level.</h4>
				</div><!-- /col12 -->
			</div><!-- /row -->
		</div><!-- /container -->
	</div><!-- /slide2 -->
<div id="aboutme">
  <br>
<div class="featurette" id="about">
            <img class="featurette-image img-circle img-responsive pull-right" src="../profilepicture.jpg">
            <h2 class="featurette-heading">Who am I
                <span class="text-muted"></span>
            </h2>
            <br>
              <p class="lead">Hello my name is Max and this is my story. <br>
              Not many people know this but I used to be a huge shy guy. <br>
              With a lot of hardwork and practice, I learned on how to build confidence <br>
              I built Confident Mindset to help others struggling and not make the <br>
              same mistakes as I was when I first started. I want everyone to be the best. <br>
              
              </p>
        </div>
        <br>
</div>
<div id="list">
  <br>
  <h2> Start Today </h2>
  <div class="cd-price">
						<span class="cd-currency">$</span>
						<span class="cd-value">5</span>
						<span class="cd-duration">/mo</span>
	</div>
<ul class="list-group">
  <li class="list-group-item">Improve your confidence</li>
  <li class="list-group-item">Redfine yourself</li>
  <li class="list-group-item">Improve relationships</li>
  <li class="list-group-item">Be more successful</li>
  <li class="list-group-item">Be the best you</li>
</ul>
<br>
<div class="frontpage">
<a href="/users/sign_up">
<button type="button" class="btn btn-primary btn-lg">Subscribe!</button>
</a>
</div>
</div>

</body>
<% end %>

app/views/pages/support.html.erb
<body id="support-page">
<div class="support">
<h1>Hello!</h1>
<h2> FAQ </h2>
<p>1. Where else can I contact you besides email?</p>
<p> You can direct message me on my instagram: <a href="https://www.instagram.com/aurigax/">aurigax</a></p>
<p>2. I cannot make payments on my smartphone? Why is that? </p>
<p> Still trying to fix that. Stripe for some reason is having issues with mobile payments at the moment. </p>
<br>
<br>
<br>
<br>
<br>
<p>Email: aurigasupport@gmail.com </p>
</div>
</body>

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put do %>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="1500"></script><span> $5 per month, cancel at any time.</span>
<% end %>       

app/views/subscribers/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/subscribers/index.html.erb
<%= render 'new' %>

app/views/subscribers/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
            <div class="panel-body">
                <h2>Final Signup Step</h2>
                <h4>This is the final step to give you full access to the program</h4>
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/subscribers/show.html.erb
<script> document.location.href="/"; </script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>